data:
  evfile : event.lst
  scfile : L241119081901FD19599832_SC00.fits

binning:
  roiwidth   : 10.0
  binsz      : 0.1
  binsperdec : 8

selection :
  emin : 100
  emax : 300000
  zmax    : 90
  evclass : 128
  evtype  : 3
  tmin    : 725760005
  tmax    : 752112005
  filter  : 'DATA_QUAL>0 && LAT_CONFIG==1'
  target : '4FGL J1555.7+1111'

gtlike:
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff','galdiff']

model:
  src_roiwidth : 15.0
  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits'
  isodiff  : '$FERMI_DIFFUSE_DIR/iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : '4FGL'
  
 
